### ISSUE TITLE
Profilepage.css - Input gradient border 1-2px wider than it should be

### ISSUE THREAD

**Issue by MakenzieRoberts** [MakenzieRoberts/Semester-2_Final-Sprint#5]
Match this border width:

![image](https://user-images.githubusercontent.com/100213075/183739902-febdbde8-9136-421e-b47f-afaf38b1e0ed.png)

To this border width:

![image](https://user-images.githubusercontent.com/100213075/183740070-d908ce55-eb5e-459e-93c7-6bb8f601795f.png)

Code responsible [**profilepage.css**] :

`.profilepage input,
.profilepage textarea {
	margin: 2px 0;
	/*Controls border gradient width*/
	width: 98%;
}`

**Comment by MakenzieRoberts** [comment]
Hey team, if you see this don't worry about it - it's just a personal reminder.

**Comment by DeToxFox** [comment]
I see it, if we have a meeting later we can chat about it.  Plus I am having a slight issue with my fork, so we can discuss that too.
